### PR TITLE
Fix disconnection Redis Server, add reconnect option configuration

### PR DESCRIPTION
**Pull request by luma777**
Without the option of reconnect the Store-Redis loses connection to Redis server.

### CODE REVIEW

**Comment by gphat** [comment]
Why remove the debug logs?

**Comment by luma777** [comment]
Logging is now only when initiated with -Debug

**Comment by gphat** [comment]
Why are you checking the debug level? The logging package takes care of that for you. That aspect of this patch doesn't seem necessary.

**Comment by luma777** [comment]
If you do not check if the application has been initialized in -Debug mode, the logs are always printed to stdout. See the code of the Session https://metacpan.org/source/JJNAPIORK/Catalyst-Plugin-Session-0.39/lib/Catalyst/Plugin/Session.pm

**Comment by gphat** [comment]
Ah.

Should I not merge this now? Why did you close it?

**Pull request closed without merging**
